#!/usr/bin/bash
IMAGE_NAME="ghcr.io/roboeagles4828/vision-devel:3"
CONTAINTER_NAME="vision-devel"
DEFAULT_CMD=""
CMD=${@:-$DEFAULT_CMD}

# Get driver config
if [[ "$1" == "stop" ]]; then
    docker stop $CONTAINTER_NAME > /dev/null 2>&1
    exit 0
fi

if [[ "$1" == "rm" ]]; then
    docker stop $CONTAINTER_NAME > /dev/null 2>&1
    docker rm $CONTAINTER_NAME > /dev/null 2>&1
    exit 0
fi

launch_vision() {
    docker run -d -t \
    --name $CONTAINTER_NAME \
    --gpus=all \
    $IMAGE_NAME sleep infinity
}


# Check if an vision container already exists
if [ $( docker ps -a | grep $CONTAINTER_NAME | wc -l ) -gt 0 ]; then
    status=$( docker container inspect -f '{{.State.Running}}' $CONTAINTER_NAME )
    if [[ "$status" == "false" ]]; then
        docker start $CONTAINTER_NAME > /dev/null 2>&1
    fi
    docker exec -it -e "DISPLAY=$DISPLAY" $CONTAINTER_NAME $CMD
else
    echo "Vision container does not exist, creating...."
    launch_vision
    docker exec -it $CONTAINTER_NAME $CMD
fi

# echo "Stopping vision..."
# docker stop $CONTAINTER_NAME > /dev/null 2>&1 &